# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs'

target 'ConnectPayBiometricExample' do
  use_frameworks!
  pod 'ConnectPay/Biometric'
end

target 'ConnectPayOCRExample' do
  use_frameworks!
  pod 'ConnectPay/OCR'
end

target 'ConnectPayExample' do
  use_frameworks!
  pod 'ConnectPay/Biometric'
  pod 'ConnectPay/OCR'
end

target 'ConnectPayUIExample' do
  use_frameworks!

  pod 'ConnectPay/UI'
end
